name: resistance-mechanisms
channels:
- conda-forge
dependencies:
- conda-forge::python=3.7.1
- conda-forge::pandas=0.25.0
- conda-forge::xlrd=1.2.0
- conda-forge::pyyaml=5.2
- conda-forge::numpy=1.16.2
- conda-forge::scikit-learn=0.20.3
- conda-forge::umap-learn=0.3.8
- conda-forge::matplotlib=3.0.3
- conda-forge::seaborn=0.9.0
- conda-forge::plotnine=0.5.1
- conda-forge::jupyter=1.0.0
- conda-forge::ipykernel=5.1.0
- conda-forge::nb_conda_kernels=2.2.1
- conda-forge::r-dplyr=0.8.3
- conda-forge::r-tidyr=0.8.3
- conda-forge::r-broom=0.5.5
- conda-forge::r-readr=1.1.1
- conda-forge::r-readxl=1.1.0
- conda-forge::r-ggplot2=3.2.1
- conda-forge::r-cowplot=1.0.0
- conda-forge::r-ggrepel=0.8.1
- conda-forge::r-svglite=1.2.2
- conda-forge::r-irkernel=1.0.2
- conda-forge::r-optparse=1.6.2
- conda-forge::r-curl=4.0
- conda-forge::r-platetools=0.1.2
- conda-forge::r-yaml=2.2.0
- pip:
  - git+https://github.com/cytomining/pycytominer@a51c76e3eb871a71ac91f86f9a99494c6ab1e4e4
