---
batch: 2019_02_15_Batch1_20X
plates:
  - HCT116bortezomib
auditcols:
  - Metadata_CellLine
  - Metadata_Dosage
auditlevel: normalized_feature_selected
process: false
---
batch: 2019_02_15_Batch1_40X
plates:
  - HCT116bortezomib
auditcols:
  - Metadata_CellLine
  - Metadata_Dosage
auditlevel: normalized_feature_selected
process: false
---
batch: 2019_03_20_Batch2
plates:
  - 207106_exposure320
auditcols:
  - Metadata_CellLine
  - Metadata_Dosage
auditlevel: normalized_feature_selected
process: false
---
batch: 2019_06_25_Batch3
plates:
  - WTClones
  - MutClones
auditcols:
  - Metadata_clone_number
auditlevel: normalized_feature_selected
process: false
---
batch: 2019_11_11_Batch4
plates:
  - WTmut04hWed
  - WTmut04hTh
auditcols:
  - Metadata_clone_number
  - Metadata_treatment
auditlevel: normalized_feature_selected
process: false
---
batch: 2019_11_19_Batch5
plates:
  - 217755
auditcols:
  - Metadata_clone_number
  - Metadata_treatment
auditlevel: normalized_feature_selected
process: false
---
batch: 2019_11_20_Batch6
plates:
  - 217760
  - 217762
auditcols:
  - Metadata_clone_number
  - Metadata_treatment
auditlevel: normalized_feature_selected
process: false
---
batch: 2019_11_22_Batch7
plates:
  - 217766
  - 217768
auditcols:
  - Metadata_clone_number
  - Metadata_treatment
auditlevel: normalized_feature_selected
process: false
---
batch: 2020_07_02_Batch8
plates:
  - 218360
  - 218361
  - 218362
  - 218363
auditcols:
  - Metadata_clone_number
  - Metadata_treatment
auditlevel: normalized_feature_selected
process: false
---
batch: 2020_08_24_Batch9
plates:
  - 218696
  - 218697
  - 218698
  - 218699
  - 218774
  - 218775
auditcols:
  - Metadata_clone_number
  - Metadata_treatment
auditlevel: normalized_feature_selected
process: false
---
batch: 2020_09_08_Batch10
plates:
  - 218852
  - 218853
  - 218854
  - 218855
  - 218856
  - 218857
  - 218858
  - 218859
auditcols:
  - Metadata_clone_number
  - Metadata_treatment
auditlevel: normalized_feature_selected
process: false
---
batch: 2021_02_08_Batch11
plates:
  - 219814  
auditcols:
  - Metadata_clone_number
  - Metadata_treatment
auditlevel: normalized_feature_selected
process: false
---
batch: 2021_03_03_Batch12
plates:
  - 219907
auditcols:
  - Metadata_clone_number
  - Metadata_treatment
auditlevel: normalized_feature_selected
process: true
---
batch: 2021_03_03_Batch13
plates:
  - 219973
auditcols:
  - Metadata_clone_number
  - Metadata_treatment
auditlevel: normalized_feature_selected
process: true
